---
- name: install docker requirements
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
  tags:
    - docker

- name: add Docker repository key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present
  tags:
    - docker

- name: add Docker armv7l repository and update apt cache
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/raspbian {{ ansible_distribution_release }} edge"
    mode: '0644'
    update_cache: yes
    state: present
  when: ansible_architecture == 'armv7l'
  tags:
    - docker

- name: install docker package
  apt:
    name: docker-ce
    state: present
  tags:
    - docker

- name: add user {{ docker_user }} to group docker
  user:
    name: "{{ docker_user }}"
    append: yes
    groups: docker
  tags:
    - docker